name: craig.camera
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5626566
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: craig.camera
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9A9A9A'
    - '#BDBDBD'
    - '#020203'
    - '#393939'
    - '#FBFBFC'
  brandStrength: 0.7811818
  lightness: 0.0989975
  saturation: 0.8897243
  rhythmicContrast: 0.2447593
purpose: []
