layout_spectrum: 1
name: craig.camera
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.7811818
  lightness: 0.0989975
  saturation: 0.8897243
  rhythmicContrast: 0.2447593
  brandColors:
    - '#9A9A9A'
    - '#BDBDBD'
    - '#020203'
    - '#393939'
    - '#FBFBFC'
typography_spectrum: 0.5626566
