color:
  brandStrength: 1
  saturation: 0.2907268
  brandColors:
    - '#030003'
    - '#FFFFFF'
    - '#0000B4'
    - '#BCC7B5'
    - '#0191F2'
  lightness: 0.07205514
  rhythmicContrast: 0.343985
title: craig.camera
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
favicon: null
layout_spectrum: 0.5056391
purpose: []
name: craig.camera
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.202381
